name: building react app and create artifact
on: [push]
jobs:
  install-and-build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: setting up node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
          npm install
          npm run build
      #- name: Archive artifacts
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: dist-without-markdown
      #    path: |
      #      build
      #      !build/**/*.md
      - run: npm run deploy